uncomment 1

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -88,168 +88,168 @@ runs:
         pytest -v tests/test_blossom.py
         pytest -v tests/test_aggregate_info.py
 
-  - name: Download and extract SDK
-    uses: nick-fields/retry@v2
-    env:
-      MODEL: gl-mt3000
-    with:
-      timeout_minutes: 6
-      max_attempts: 3
-      command: |
-        VERSION=23.05.3
-
-        # Determine PLATFORM and SUBTARGET based on MODEL (same logic as in build-firmware)
-        case "${{ env.MODEL }}" in
-          "gl-mt300n-v2")
-            PLATFORM="ramips"
-            SUBTARGET="mt76x8"
-            ;;
-          "gl-ar300m")
-            PLATFORM="ath79"
-            SUBTARGET="generic"
-            ;;
-          "gl-mt3000"|"gl-mt6000")
-            PLATFORM="mediatek"
-            SUBTARGET="filogic"
-            ;;
-          "gl-e750")
-            VERSION="snapshot"
-            PLATFORM="ath79"
-            SUBTARGET="nand"
-            ;;
-          "archer_mr200")
-            PLATFORM="ramips"
-            SUBTARGET="mt7620"
-            ;;
-          *)
-            echo "Unsupported model"
-            exit 1
-            ;;
-        esac
-        echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
-        echo "SUBTARGET=$SUBTARGET" >> $GITHUB_ENV
-        SDKDIR=/tmp/openwrt-sdk
-        SDK_ARCHIVE="openwrt-sdk-${VERSION}-${PLATFORM}-${SUBTARGET}_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
-        DOWNLOAD_URL="https://downloads.openwrt.org/releases/${VERSION}/targets/${PLATFORM}/${SUBTARGET}/${SDK_ARCHIVE}"
-        SDK_PATH="${SDKDIR}/openwrt-sdk-${VERSION}-${PLATFORM}-${SUBTARGET}_gcc-12.3.0_musl.Linux-x86_64"
-        echo "SDK_PATH=$SDK_PATH" >> $GITHUB_ENV
-        if [ ! -d "${SDKDIR}" ] ; then
-          mkdir -p "${SDKDIR}"
-        fi
-        if [ ! -f "${SDKDIR}/${SDK_ARCHIVE}" ]; then
-          echo "Downloading SDK..."
-          (cd "${SDKDIR}" && curl -O "${DOWNLOAD_URL}")
-        fi
-        echo "Extracting SDK..."
-        tar -I "xz -T0" -xf "${SDKDIR}/${SDK_ARCHIVE}" -C "${SDKDIR}"
-        echo "Copying golang.mk to SDK include directory..."
-        mkdir -p "${SDK_PATH}"/include
-        cp "${SCRIPT_DIR}"/golang.mk "${SDK_PATH}"/include/golang.mk
-
-        # Set GOOS and GOARCH based on the PLATFORM variable
-        case "$PLATFORM" in
-          "ramips")
-            export GOOS="linux"
-            export GOARCH="mips"
-            if [ "$SUBTARGET" = "mt7620" ]; then
-              export GOARM=""
-              export GOMIPS="mips32"
-              export GO386=""
-            else
-              export GOARM=""
-              export GOMIPS="mips32"
-              export GO386=""
-            fi
-            ;;
-          "ath79")
-            export GOOS="linux"
-            export GOARCH="mips"
-            export GOARM=""
-            export GOMIPS="mips32"
-            export GO386=""
-            ;;
-          "mediatek")
-            export GOOS="linux"
-            export GOARCH="arm64"
-            export GOARM="arm64"
-            export GOMIPS=""
-            export GO386=""
-            ;;
-          *)
-            echo "Unsupported platform for GOOS/GOARCH setting."
-            exit 1
-            ;;
-        esac
-
-        echo "Setting up python environment..."
-        if [ ! -f "${SDK_PATH}/staging_dir/host/bin/opkg-make-index" ]; then
-          echo "Installing opkg-make-index..."
-          mkdir -p "${SDK_PATH}/staging_dir/host/bin"
-          wget https://raw.githubusercontent.com/shr-project/opkg-utils/master/opkg-make-index -O "${SDK_PATH}/staging_dir/host/bin/opkg-make-index"
-          chmod +x "${SDK_PATH}/staging_dir/host/bin/opkg-make-index"
-        fi
-
-#          cp "${SCRIPT_DIR}"/feeds.conf "${SDK_PATH}"/feeds.conf
-        cd "${SDK_PATH}"
-        ./scripts/feeds update -a
-        ./scripts/feeds install -a
-
-  - name: Copy makefile into SDK
-    id: copy_makefile_step
-    uses: nick-fields/retry@v2
-    with:
-      timeout_minutes: 5
-      max_attempts: 3
-      command: |
-        ls -R
-        cp lang package/feeds/custom/${{ inputs.packageName }}/compile
-        cp ${{ inputs.makeFilePath }} package/feeds/custom/${{ inputs.packageName }}/compile
-
-  - name: Build firmware
-    id: build_firmware_step
-    env:
-      MODEL: gl-mt3000
-      PLATFORM: ${{ env.PLATFORM }}
-      SUBTARGET: ${{ env.SUBTARGET }}
-    uses: nick-fields/retry@v2
-    with:
-      timeout_minutes: 5
-      max_attempts: 3
-      command: |
-        echo "python3 aggregate_info.py ${{ env.BUILT_PACKAGES_DIR }} ${{ env.SCRIPT_DIR }}/feeds.conf ${{ env.SDK_PATH }}"
-        python3 aggregate_info.py "${{ env.BUILT_PACKAGES_DIR }}" "${{ env.SCRIPT_DIR }}/feeds.conf" "${{ env.SDK_PATH }}"
-
-  - name: Build firmware2
-    env:
-      MODEL: gl-mt3000
-      PLATFORM: ${{ env.PLATFORM }}
-      SUBTARGET: ${{ env.SUBTARGET }}
-    uses: nick-fields/retry@v2
-    with:
-      timeout_minutes: 18
-      max_attempts: 3
-      command: |
-        VERSION=23.05.3
-        MODULE=${{ inputs.packageName }}
-        SDKDIR=/tmp/openwrt-sdk
-        SDK_PATH="${SDKDIR}/openwrt-sdk-${VERSION}-${PLATFORM}-${SUBTARGET}_gcc-12.3.0_musl.Linux-x86_64"
-        cd "${SDK_PATH}"
-        make defconfig
-        make package/feeds/custom/golang/compile V=sc
-        make package/feeds/custom/${{ inputs.packageName }}/compile V=sc
-        BUILT_PACKAGES_DIR=$(find "${SDK_PATH}/bin/packages" -name "tollgate-module-*.ipk" | xargs dirname | head -n 1)
-        echo "BUILT_PACKAGES_DIR=$BUILT_PACKAGES_DIR" >> $GITHUB_ENV
-        echo "SCRIPT_DIR=$SCRIPT_DIR" >> $GITHUB_ENV
-
-  - name: Run aggregate_info
-    env:
-      BUILT_PACKAGES_DIR: ${{ env.BUILT_PACKAGES_DIR }}
-      SCRIPT_DIR: ${{ env.SCRIPT_DIR }}
-      SDK_PATH: ${{ env.SDK_PATH }}
-    uses: nick-fields/retry@v2
-    with:
-      timeout_minutes: 5
-      max_attempts: 3
-      command: |
-        echo "python3 aggregate_info.py ${{ env.BUILT_PACKAGES_DIR }} ${{ env.SCRIPT_DIR }}/feeds.conf ${{ env.SDK_PATH }}"
-        python3 aggregate_info.py "${{ env.BUILT_PACKAGES_DIR }}" "${{ env.SCRIPT_DIR }}/feeds.conf" "${{ env.SDK_PATH }}"
+#  - name: Download and extract SDK
+#    uses: nick-fields/retry@v2
+#    env:
+#      MODEL: gl-mt3000
+#    with:
+#      timeout_minutes: 6
+#      max_attempts: 3
+#      command: |
+#        VERSION=23.05.3
+#
+#        # Determine PLATFORM and SUBTARGET based on MODEL (same logic as in build-firmware)
+#        case "${{ env.MODEL }}" in
+#          "gl-mt300n-v2")
+#            PLATFORM="ramips"
+#            SUBTARGET="mt76x8"
+#            ;;
+#          "gl-ar300m")
+#            PLATFORM="ath79"
+#            SUBTARGET="generic"
+#            ;;
+#          "gl-mt3000"|"gl-mt6000")
+#            PLATFORM="mediatek"
+#            SUBTARGET="filogic"
+#            ;;
+#          "gl-e750")
+#            VERSION="snapshot"
+#            PLATFORM="ath79"
+#            SUBTARGET="nand"
+#            ;;
+#          "archer_mr200")
+#            PLATFORM="ramips"
+#            SUBTARGET="mt7620"
+#            ;;
+#          *)
+#            echo "Unsupported model"
+#            exit 1
+#            ;;
+#        esac
+#        echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
+#        echo "SUBTARGET=$SUBTARGET" >> $GITHUB_ENV
+#        SDKDIR=/tmp/openwrt-sdk
+#        SDK_ARCHIVE="openwrt-sdk-${VERSION}-${PLATFORM}-${SUBTARGET}_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
+#        DOWNLOAD_URL="https://downloads.openwrt.org/releases/${VERSION}/targets/${PLATFORM}/${SUBTARGET}/${SDK_ARCHIVE}"
+#        SDK_PATH="${SDKDIR}/openwrt-sdk-${VERSION}-${PLATFORM}-${SUBTARGET}_gcc-12.3.0_musl.Linux-x86_64"
+#        echo "SDK_PATH=$SDK_PATH" >> $GITHUB_ENV
+#        if [ ! -d "${SDKDIR}" ] ; then
+#          mkdir -p "${SDKDIR}"
+#        fi
+#        if [ ! -f "${SDKDIR}/${SDK_ARCHIVE}" ]; then
+#          echo "Downloading SDK..."
+#          (cd "${SDKDIR}" && curl -O "${DOWNLOAD_URL}")
+#        fi
+#        echo "Extracting SDK..."
+#        tar -I "xz -T0" -xf "${SDKDIR}/${SDK_ARCHIVE}" -C "${SDKDIR}"
+#        echo "Copying golang.mk to SDK include directory..."
+#        mkdir -p "${SDK_PATH}"/include
+#        cp "${SCRIPT_DIR}"/golang.mk "${SDK_PATH}"/include/golang.mk
+#
+#        # Set GOOS and GOARCH based on the PLATFORM variable
+#        case "$PLATFORM" in
+#          "ramips")
+#            export GOOS="linux"
+#            export GOARCH="mips"
+#            if [ "$SUBTARGET" = "mt7620" ]; then
+#              export GOARM=""
+#              export GOMIPS="mips32"
+#              export GO386=""
+#            else
+#              export GOARM=""
+#              export GOMIPS="mips32"
+#              export GO386=""
+#            fi
+#            ;;
+#          "ath79")
+#            export GOOS="linux"
+#            export GOARCH="mips"
+#            export GOARM=""
+#            export GOMIPS="mips32"
+#            export GO386=""
+#            ;;
+#          "mediatek")
+#            export GOOS="linux"
+#            export GOARCH="arm64"
+#            export GOARM="arm64"
+#            export GOMIPS=""
+#            export GO386=""
+#            ;;
+#          *)
+#            echo "Unsupported platform for GOOS/GOARCH setting."
+#            exit 1
+#            ;;
+#        esac
+#
+#        echo "Setting up python environment..."
+#        if [ ! -f "${SDK_PATH}/staging_dir/host/bin/opkg-make-index" ]; then
+#          echo "Installing opkg-make-index..."
+#          mkdir -p "${SDK_PATH}/staging_dir/host/bin"
+#          wget https://raw.githubusercontent.com/shr-project/opkg-utils/master/opkg-make-index -O "${SDK_PATH}/staging_dir/host/bin/opkg-make-index"
+#          chmod +x "${SDK_PATH}/staging_dir/host/bin/opkg-make-index"
+#        fi
+#
+##          cp "${SCRIPT_DIR}"/feeds.conf "${SDK_PATH}"/feeds.conf
+#        cd "${SDK_PATH}"
+#        ./scripts/feeds update -a
+#        ./scripts/feeds install -a
+#
+#  - name: Copy makefile into SDK
+#    id: copy_makefile_step
+#    uses: nick-fields/retry@v2
+#    with:
+#      timeout_minutes: 5
+#      max_attempts: 3
+#      command: |
+#        ls -R
+#        cp lang package/feeds/custom/${{ inputs.packageName }}/compile
+#        cp ${{ inputs.makeFilePath }} package/feeds/custom/${{ inputs.packageName }}/compile
+#
+#  - name: Build firmware
+#    id: build_firmware_step
+#    env:
+#      MODEL: gl-mt3000
+#      PLATFORM: ${{ env.PLATFORM }}
+#      SUBTARGET: ${{ env.SUBTARGET }}
+#    uses: nick-fields/retry@v2
+#    with:
+#      timeout_minutes: 5
+#      max_attempts: 3
+#      command: |
+#        echo "python3 aggregate_info.py ${{ env.BUILT_PACKAGES_DIR }} ${{ env.SCRIPT_DIR }}/feeds.conf ${{ env.SDK_PATH }}"
+#        python3 aggregate_info.py "${{ env.BUILT_PACKAGES_DIR }}" "${{ env.SCRIPT_DIR }}/feeds.conf" "${{ env.SDK_PATH }}"
+#
+#  - name: Build firmware2
+#    env:
+#      MODEL: gl-mt3000
+#      PLATFORM: ${{ env.PLATFORM }}
+#      SUBTARGET: ${{ env.SUBTARGET }}
+#    uses: nick-fields/retry@v2
+#    with:
+#      timeout_minutes: 18
+#      max_attempts: 3
+#      command: |
+#        VERSION=23.05.3
+#        MODULE=${{ inputs.packageName }}
+#        SDKDIR=/tmp/openwrt-sdk
+#        SDK_PATH="${SDKDIR}/openwrt-sdk-${VERSION}-${PLATFORM}-${SUBTARGET}_gcc-12.3.0_musl.Linux-x86_64"
+#        cd "${SDK_PATH}"
+#        make defconfig
+#        make package/feeds/custom/golang/compile V=sc
+#        make package/feeds/custom/${{ inputs.packageName }}/compile V=sc
+#        BUILT_PACKAGES_DIR=$(find "${SDK_PATH}/bin/packages" -name "tollgate-module-*.ipk" | xargs dirname | head -n 1)
+#        echo "BUILT_PACKAGES_DIR=$BUILT_PACKAGES_DIR" >> $GITHUB_ENV
+#        echo "SCRIPT_DIR=$SCRIPT_DIR" >> $GITHUB_ENV
+#
+#  - name: Run aggregate_info
+#    env:
+#      BUILT_PACKAGES_DIR: ${{ env.BUILT_PACKAGES_DIR }}
+#      SCRIPT_DIR: ${{ env.SCRIPT_DIR }}
+#      SDK_PATH: ${{ env.SDK_PATH }}
+#    uses: nick-fields/retry@v2
+#    with:
+#      timeout_minutes: 5
+#      max_attempts: 3
+#      command: |
+#        echo "python3 aggregate_info.py ${{ env.BUILT_PACKAGES_DIR }} ${{ env.SCRIPT_DIR }}/feeds.conf ${{ env.SDK_PATH }}"
+#        python3 aggregate_info.py "${{ env.BUILT_PACKAGES_DIR }}" "${{ env.SCRIPT_DIR }}/feeds.conf" "${{ env.SDK_PATH }}"
