Upgrade bootstrap compiler

diff --git a/custom_feeds/packages/lang/golang/golang/Makefile b/custom_feeds/packages/lang/golang/golang/Makefile
--- a/custom_feeds/packages/lang/golang/golang/Makefile
+++ b/custom_feeds/packages/lang/golang/golang/Makefile
@@ -7,9 +7,12 @@
 
 include $(TOPDIR)/rules.mk
 
+# Update these lines at the top
 GO_VERSION_MAJOR_MINOR:=1.23
 GO_VERSION_PATCH:=4
-export GOROOT_BOOTSTRAP=/opt/go1.20.6
+
+# Add this line to explicitly set the minimum bootstrap version
+GO_BOOTSTRAP_VERSION:=1.20.6
 
 PKG_NAME:=golang
 PKG_VERSION:=$(GO_VERSION_MAJOR_MINOR)$(if $(GO_VERSION_PATCH),.$(GO_VERSION_PATCH))
@@ -74,9 +77,12 @@ HOST_GO_VALID_OS_ARCH:= \
   \
   openbsd_mips64
 
-BOOTSTRAP_SOURCE:=go1.4-bootstrap-20171003.tar.gz
-BOOTSTRAP_SOURCE_URL:=$(GO_SOURCE_URLS)
-BOOTSTRAP_HASH:=f4ff5b5eb3a3cae1c993723f3eab519c5bae18866b5e5f96fe1102f0cb5c3e52
+# Replace the old bootstrap definitions
+BOOTSTRAP_1_20_SOURCE:=go1.20.6.src.tar.gz
+BOOTSTRAP_1_20_SOURCE_URL:=$(GO_SOURCE_URLS)
+BOOTSTRAP_1_20_HASH:=b9b2d84e128c04f45d5a55081173b77f28b9843cd086f22d6c3727b37805f
+
+BOOTSTRAP_1_20_BUILD_DIR:=$(HOST_BUILD_DIR)/.go_bootstrap_1_20
 
 BOOTSTRAP_BUILD_DIR:=$(HOST_BUILD_DIR)/.go_bootstrap
 
@@ -91,11 +97,11 @@ BOOTSTRAP_GO_VALID_OS_ARCH:= \
                  solaris_amd64 \
   windows_386    windows_amd64
 
-BOOTSTRAP_1_17_SOURCE:=go1.17.13.src.tar.gz
-BOOTSTRAP_1_17_SOURCE_URL:=$(GO_SOURCE_URLS)
-BOOTSTRAP_1_17_HASH:=a1a48b23afb206f95e7bbaa9b898d965f90826f6f1d1fc0c1d784ada0cd300fd
+# BOOTSTRAP_1_17_SOURCE:=go1.17.13.src.tar.gz
+# BOOTSTRAP_1_17_SOURCE_URL:=$(GO_SOURCE_URLS)
+# BOOTSTRAP_1_17_HASH:=a1a48b23afb206f95e7bbaa9b898d965f90826f6f1d1fc0c1d784ada0cd300fd
 
-BOOTSTRAP_1_17_BUILD_DIR:=$(HOST_BUILD_DIR)/.go_bootstrap_1.17
+# BOOTSTRAP_1_17_BUILD_DIR:=$(HOST_BUILD_DIR)/.go_bootstrap_1.17
 
 include $(INCLUDE_DIR)/host-build.mk
 include $(INCLUDE_DIR)/package.mk
@@ -192,30 +198,31 @@ ifeq ($(BOOTSTRAP_ROOT_DIR),)
   endef
   $(eval $(call Download,golang-bootstrap))
 
-  define Bootstrap/Prepare
-	mkdir -p "$(BOOTSTRAP_BUILD_DIR)" && $(BOOTSTRAP_UNPACK) ;
+  # Replace the old Bootstrap-1.17 prepare definition
+  define Bootstrap-1.20/Prepare
+          mkdir -p "$(BOOTSTRAP_1_20_BUILD_DIR)" && $(HOST_TAR) -C "$(BOOTSTRAP_1_20_BUILD_DIR)" --strip-components=1 -xzf "$(DL_DIR)/$(BOOTSTRAP_1_20_SOURCE)" ;
   endef
-  Hooks/HostPrepare/Post+=Bootstrap/Prepare
+  Hooks/HostPrepare/Post+=Bootstrap-1.20/Prepare
 
   $(eval $(call GoCompiler/AddProfile,Bootstrap,$(BOOTSTRAP_BUILD_DIR),,bootstrap,$(GO_HOST_OS_ARCH)))
 endif
 
 
-# Bootstrap 1.17
+# Bootstrap 1.20
 
-define Download/golang-bootstrap-1.17
-  FILE:=$(BOOTSTRAP_1_17_SOURCE)
-  URL:=$(BOOTSTRAP_1_17_SOURCE_URL)
-  HASH:=$(BOOTSTRAP_1_17_HASH)
+define Download/golang-bootstrap-1.20
+  FILE:=$(BOOTSTRAP_1_20_SOURCE)
+  URL:=$(BOOTSTRAP_1_20_SOURCE_URL)
+  HASH:=$(BOOTSTRAP_1_20_HASH)
 endef
-$(eval $(call Download,golang-bootstrap-1.17))
+$(eval $(call Download,golang-bootstrap-1.20))
 
 define Bootstrap-1.17/Prepare
 	mkdir -p "$(BOOTSTRAP_1_17_BUILD_DIR)" && $(BOOTSTRAP_1_17_UNPACK) ;
 endef
 Hooks/HostPrepare/Post+=Bootstrap-1.17/Prepare
 
-$(eval $(call GoCompiler/AddProfile,Bootstrap-1.17,$(BOOTSTRAP_1_17_BUILD_DIR),,bootstrap-1.17,$(GO_HOST_OS_ARCH)))
+$(eval $(call GoCompiler/AddProfile,Bootstrap-1.20,$(BOOTSTRAP_1_20_BUILD_DIR),,bootstrap-1.20,$(GO_HOST_OS_ARCH)))
 
 
 # Host
@@ -236,6 +243,14 @@ HOST_GO_VARS= \
 	CC="$(HOSTCC_NOCACHE)" \
 	CXX="$(HOSTCXX_NOCACHE)"
 
+define GoCompiler/Bootstrap/CheckVersion
+        # Add version check logic
+        if [ "$(GO_BOOTSTRAP_VERSION)" \< "1.20.6" ]; then \
+                echo "Error: Go bootstrap version must be at least 1.20.6" >&2; \
+                exit 1; \
+        fi
+endef
+
 define Host/Configure
 	$(call GoCompiler/Bootstrap/CheckHost,$(BOOTSTRAP_GO_VALID_OS_ARCH))
 	$(call GoCompiler/Host/CheckHost,$(HOST_GO_VALID_OS_ARCH))
@@ -244,20 +259,20 @@ define Host/Configure
 endef
 
 define Host/Compile
-	$(call GoCompiler/Bootstrap/Make, \
-		$(HOST_GO_VARS) \
-	)
+        $(call GoCompiler/Bootstrap/Make, \
+                $(HOST_GO_VARS) \
+        )
 
-	$(call GoCompiler/Bootstrap-1.17/Make, \
-		GOROOT_BOOTSTRAP="$(BOOTSTRAP_ROOT_DIR)" \
-		$(HOST_GO_VARS) \
-	)
+        $(call GoCompiler/Bootstrap-1.20/Make, \
+                GOROOT_BOOTSTRAP="$(BOOTSTRAP_ROOT_DIR)" \
+                $(HOST_GO_VARS) \
+        )
 
-	$(call GoCompiler/Host/Make, \
-		GOROOT_BOOTSTRAP="$(BOOTSTRAP_1_17_BUILD_DIR)" \
-		$(if $(HOST_GO_ENABLE_PIE),GO_LDFLAGS="-buildmode pie") \
-		$(HOST_GO_VARS) \
-	)
+        $(call GoCompiler/Host/Make, \
+                GOROOT_BOOTSTRAP="$(BOOTSTRAP_1_20_BUILD_DIR)" \
+                $(if $(HOST_GO_ENABLE_PIE),GO_LDFLAGS="-buildmode pie") \
+                $(HOST_GO_VARS) \
+        )
 endef
 
 # if host and target os/arch are the same,
